set(CMAKE_C_FLAGS "-Dchar16_t=uint16_t")

if(MSVC)
  set(CMAKE_CXX_FLAGS "/utf-8")
endif()


add_compile_definitions(U_COMMON_IMPLEMENTATION)
add_compile_definitions(U_I18N_IMPLEMENTATION)
add_compile_definitions(U_STATIC_IMPLEMENTATION)
add_compile_definitions(U_USING_ICU_NAMESPACE=1)
add_compile_definitions(UCONFIG_NO_FILE_IO=1)
add_compile_definitions(U_NO_DEFAULT_INCLUDE_UTF_HEADERS=0)
add_compile_definitions(U_HAVE_NL_LANGINFO_CODESET=0)
add_compile_definitions(U_TIMEZONE=0)
add_compile_definitions(UCONFIG_NO_LEGACY_CONVERSION=1)
add_compile_definitions(U_ENABLE_DYLOAD=0)
add_compile_definitions(U_CHECK_DYLOAD=0)
add_compile_definitions(UCONFIG_NO_SERVICE=1)
# add_compile_definitions(U_USING_ICU_NAMESPACE=1)


include_directories("${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common")
include_directories("${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n")


# Common objects for static and shared library

set(ICU_SOURCES
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/bmpset.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/brkeng.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/bytesinkutil.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/capi_helper.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/charstr.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/charstrmap.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/cmemory.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/common.rc
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/cpputils.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/cstr.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/cstring.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/cwchar.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/dictbe.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/dictionarydata.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/emojiprops.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/hash.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/icuplugimp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/localeprioritylist.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/localsvc.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/locbased.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/locdistance.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/loclikelysubtags.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/locmap.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/locutil.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/lsr.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/lstmbe.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/messageimpl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/msvcres.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/mutex.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/norm2_nfc_data.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/norm2allmodes.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/normalizer2impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/patternprops.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/pluralmap.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/propname.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/propname_data.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/propsvec.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/punycode.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/putilimp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbi_cache.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbidata.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbinode.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbirb.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbirpt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbiscan.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbisetb.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbitblb.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/resource.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/restrace.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ruleiter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/serv.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/servloc.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/servnotf.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/sharedobject.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/sprpimpl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/static_unicode_sets.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uarrsort.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uassert.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ubidi_props.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ubidi_props_data.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ubidiimp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ubrkimpl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucase.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucase_props_data.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucasemap_imp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uchar_props_data.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucln.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucln_cmn.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucln_imp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucmndata.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_bld.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_cnv.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_ext.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_imp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_io.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnvmbcs.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucol_data.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucol_swp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucptrie_impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucurrimp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/udatamem.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/udataswp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uelement.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uenumimp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uhash.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uinvchar.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ulayout_props.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ulist.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ulocimp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/umapfile.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/umutex.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/appendable.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/brkiter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/bytestream.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/bytestrie.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/bytestriebuilder.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/caniter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/casemap.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/char16ptr.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/chariter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/dbbi.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/docmain.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/dtintrv.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/edits.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/enumset.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/errorcode.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/filteredbrk.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/icudataver.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/icuplug.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/idna.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/localebuilder.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/localematcher.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/localpointer.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/locdspnm.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/locid.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/messagepattern.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/normalizer2.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/normlzr.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/parseerr.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/parsepos.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/platform.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ptypes.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/putil.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/rbbi.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/rep.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/resbund.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/schriter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/simpleformatter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/std_string.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/strenum.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/stringoptions.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/stringpiece.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/stringtriebuilder.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/symtable.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ubidi.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ubiditransform.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ubrk.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ucasemap.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ucat.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/uchar.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ucharstrie.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ucharstriebuilder.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/uchriter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/uclean.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ucnv.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ucnv_cb.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ucnv_err.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ucnvsel.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/uconfig.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ucpmap.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ucptrie.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ucurr.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/udata.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/udisplaycontext.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/uenum.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/uidna.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/uiter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/uldnames.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/uloc.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/umachine.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/umisc.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/umutablecptrie.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/unifilt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/unifunct.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/unimatch.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/uniset.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/unistr.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/unorm.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/unorm2.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/uobject.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/urename.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/urep.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ures.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/uscript.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/uset.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/usetiter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ushape.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/usprep.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ustring.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/ustringtrie.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/utext.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/utf.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/utf16.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/utf32.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/utf8.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/utf_old.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/utrace.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/utypes.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/uvernum.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unicode/uversion.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unifiedcache.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uniquecharstr.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unisetspan.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unistrappender.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unormimp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uposixdefs.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uprops.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uresdata.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uresimp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ureslocs.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/usc_impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uset_imp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ustr_cnv.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ustr_imp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ustrenum.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ustrfmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/util.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/utracimp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/utrie.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/utrie2.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/utrie2_impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/utypeinfo.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uvector.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uvectr32.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uvectr64.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/wintz.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/anytrans.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/astro.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/bocsu.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/brktrans.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/buddhcal.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/casetrn.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/cecal.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/chnsecal.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collation.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationbuilder.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationcompare.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationdata.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationdatabuilder.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationdatareader.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationdatawriter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationfastlatin.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationfastlatinbuilder.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationfcd.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationiterator.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationkeys.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationroot.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationrootelements.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationruleparser.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationsets.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationsettings.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationtailoring.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationweights.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collunsafe.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/coptccal.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/cpdtrans.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/csdetect.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/csmatch.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/csr2022.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/csrecog.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/csrmbcs.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/csrsbcs.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/csrucode.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/csrutf8.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/currfmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/dangical.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/dayperiodrules.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/decContext.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/decNumber.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/decNumberLocal.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-bignum-dtoa.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-bignum.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-cached-powers.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-diy-fp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-double-to-string.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-fast-dtoa.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-ieee.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-string-to-double.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-strtod.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-utils.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/dt_impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/dtitv_impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/dtptngen_impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/erarules.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/esctrn.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/ethpccal.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/fmtableimp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/formatted_string_builder.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/formattedval_impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/fphdlimp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/funcrepl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/gregoimp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/hebrwcal.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/i18n.rc
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/indiancal.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/inputext.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/islamcal.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/japancal.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/measunit_impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/msgfmt_impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/name2uni.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/nfrlist.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/nfrs.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/nfrule.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/nfsubs.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/nortrans.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/nultrans.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_affixutils.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_asformat.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_compact.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_currencysymbols.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_decimalquantity.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_decimfmtprops.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_decnum.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_formatimpl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_longnames.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_mapper.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_microprops.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_modifiers.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_multiplier.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_patternmodifier.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_patternstring.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_roundingutils.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_scientific.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_skeletons.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_types.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_usageprefs.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_utils.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_utypes.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_affixes.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_compositions.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_currency.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_decimal.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_scientific.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_symbols.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_types.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_utils.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_validators.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numrange_impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numsys_impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/olsontz.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/persncal.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/pluralranges.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/plurrule_impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/quant.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/quantityformatter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/rbt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/rbt_data.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/rbt_pars.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/rbt_rule.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/rbt_set.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/regexcmp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/regexcst.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/regeximp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/regexst.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/regextxt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/region_impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/reldtfmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/remtrans.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/scriptset.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/selfmtimpl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/sharedbreakiterator.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/sharedcalendar.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/shareddateformatsymbols.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/sharednumberformat.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/sharedpluralrules.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/smpdtfst.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/standardplural.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/string_segment.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/strmatch.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/strrepl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/taiwncal.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/titletrn.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/tolowtrn.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/toupptrn.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/transreg.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/tridpars.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/tzgnames.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/tznames_impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/ucln_in.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/ucol_imp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/uitercollationiterator.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/umsg_imp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unesctrn.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/uni2name.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/alphaindex.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/basictz.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/calendar.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/choicfmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/coleitr.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/coll.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/compactdecimalformat.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/curramt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/currpinf.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/currunit.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/datefmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/dcfmtsym.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/decimfmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/dtfmtsym.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/dtitvfmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/dtitvinf.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/dtptngen.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/dtrule.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/fieldpos.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/fmtable.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/format.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/formattedvalue.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/fpositer.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/gender.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/gregocal.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/listformatter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/measfmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/measunit.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/measure.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/msgfmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/nounit.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/numberformatter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/numberrangeformatter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/numfmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/numsys.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/plurfmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/plurrule.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/rbnf.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/rbtz.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/regex.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/region.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/reldatefmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/scientificnumberformatter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/search.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/selfmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/simpletz.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/smpdtfmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/sortkey.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/stsearch.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/tblcoll.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/timezone.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/tmunit.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/tmutamt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/tmutfmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/translit.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/tzfmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/tznames.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/tzrule.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/tztrans.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/ucal.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/ucol.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/ucoleitr.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/ucsdet.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/udat.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/udateintervalformat.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/udatpg.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/ufieldpositer.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/uformattable.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/uformattedvalue.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/ugender.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/ulistformatter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/ulocdata.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/umsg.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/unirepl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/unounclass.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/unum.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/unumberformatter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/unumberrangeformatter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/unumsys.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/upluralrules.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/uregex.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/uregion.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/ureldatefmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/usearch.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/uspoof.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/utmscale.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/utrans.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unicode/vtzone.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/units_complexconverter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/units_converter.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/units_data.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/units_router.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/uspoof_conf.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/uspoof_impl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/usrchimp.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/utf16collationiterator.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/utf8collationiterator.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/vzone.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/windtfmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/winnmfmt.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/wintzimpl.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/zonemeta.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/zrule.h
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/ztrans.h
)

list(APPEND ICU_SOURCES
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/appendable.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/bmpset.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/brkeng.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/brkiter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/bytesinkutil.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/bytestream.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/bytestrie.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/bytestriebuilder.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/bytestrieiterator.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/caniter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/characterproperties.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/chariter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/charstr.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/cmemory.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/cstr.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/cstring.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/cwchar.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/dictbe.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/dictionarydata.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/dtintrv.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/edits.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/emojiprops.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/errorcode.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/filteredbrk.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/filterednormalizer2.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/icudataver.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/icuplug.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/loadednormalizer2impl.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/localebuilder.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/localematcher.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/localeprioritylist.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/locavailable.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/locbased.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/locdispnames.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/locdistance.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/locdspnm.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/locid.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/loclikely.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/loclikelysubtags.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/locmap.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/locresdata.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/locutil.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/lsr.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/lstmbe.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/messagepattern.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/normalizer2.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/normalizer2impl.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/normlzr.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/parsepos.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/patternprops.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/pluralmap.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/propname.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/propsvec.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/punycode.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/putil.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbi.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbi_cache.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbidata.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbinode.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbirb.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbiscan.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbisetb.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbistbl.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/rbbitblb.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/resbund.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/resbund_cnv.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/resource.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/restrace.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ruleiter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/schriter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/serv.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/servlk.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/servlkf.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/servls.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/servnotf.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/servrbf.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/servslkf.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/sharedobject.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/simpleformatter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/static_unicode_sets.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/stringpiece.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/stringtriebuilder.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uarrsort.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ubidi.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ubidi_props.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ubidiln.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ubiditransform.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ubidiwrt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ubrk.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucase.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucasemap.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucasemap_titlecase_brkiter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucat.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uchar.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucharstrie.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucharstriebuilder.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucharstrieiterator.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uchriter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucln_cmn.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucmndata.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv2022.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_bld.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_cb.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_cnv.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_ct.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_err.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_ext.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_io.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_lmb.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_set.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_u16.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_u32.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_u7.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnv_u8.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnvbocu.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnvdisp.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnvhz.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnvisci.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnvlat1.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnvmbcs.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnvscsu.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucnvsel.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucol_swp.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucptrie.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ucurr.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/udata.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/udatamem.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/udataswp.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uenum.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uhash.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uhash_us.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uidna.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uinit.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uinvchar.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uiter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ulist.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uloc.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uloc_keytype.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uloc_tag.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/umapfile.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/umath.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/umutablecptrie.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/umutex.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unames.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unifiedcache.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unifilt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unifunct.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uniset.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uniset_closure.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uniset_props.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unisetspan.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unistr.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unistr_case.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unistr_case_locale.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unistr_cnv.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unistr_props.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unistr_titlecase_brkiter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unorm.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/unormcmp.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uobject.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uprops.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ures_cnv.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uresbund.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uresdata.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/usc_impl.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uscript.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uscript_props.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uset.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uset_props.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/usetiter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ushape.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/usprep.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ustack.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ustr_cnv.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ustr_titlecase_brkiter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ustr_wcs.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ustrcase.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ustrcase_locale.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ustrenum.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ustrfmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ustring.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/ustrtrns.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/utext.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/utf_impl.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/util.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/util_props.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/utrace.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/utrie.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/utrie2.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/utrie2_builder.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/utrie_swap.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uts46.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/utypes.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uvector.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uvectr32.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/uvectr64.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/common/wintz.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/alphaindex.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/anytrans.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/astro.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/basictz.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/bocsu.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/brktrans.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/buddhcal.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/calendar.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/casetrn.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/cecal.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/chnsecal.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/choicfmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/coleitr.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/coll.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collation.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationbuilder.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationcompare.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationdata.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationdatabuilder.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationdatareader.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationdatawriter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationfastlatin.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationfastlatinbuilder.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationfcd.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationiterator.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationkeys.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationroot.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationrootelements.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationruleparser.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationsets.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationsettings.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationtailoring.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/collationweights.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/compactdecimalformat.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/coptccal.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/cpdtrans.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/csdetect.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/csmatch.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/csr2022.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/csrecog.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/csrmbcs.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/csrsbcs.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/csrucode.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/csrutf8.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/curramt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/currfmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/currpinf.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/currunit.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/dangical.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/datefmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/dayperiodrules.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/dcfmtsym.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/decContext.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/decNumber.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/decimfmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-bignum-dtoa.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-bignum.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-cached-powers.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-double-to-string.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-fast-dtoa.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-string-to-double.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/double-conversion-strtod.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/dtfmtsym.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/dtitvfmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/dtitvinf.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/dtptngen.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/dtrule.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/erarules.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/esctrn.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/ethpccal.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/fmtable.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/fmtable_cnv.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/format.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/formatted_string_builder.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/formattedval_iterimpl.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/formattedval_sbimpl.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/formattedvalue.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/fphdlimp.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/fpositer.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/funcrepl.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/gender.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/gregocal.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/gregoimp.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/hebrwcal.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/indiancal.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/inputext.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/islamcal.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/japancal.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/listformatter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/measfmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/measunit.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/measunit_extra.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/measure.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/msgfmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/name2uni.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/nfrs.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/nfrule.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/nfsubs.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/nortrans.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/nultrans.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_affixutils.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_asformat.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_capi.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_compact.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_currencysymbols.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_decimalquantity.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_decimfmtprops.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_fluent.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_formatimpl.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_grouping.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_integerwidth.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_longnames.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_mapper.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_modifiers.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_multiplier.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_notation.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_output.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_padding.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_patternmodifier.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_patternstring.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_rounding.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_scientific.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_skeletons.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_symbolswrapper.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_usageprefs.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/number_utils.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numfmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_affixes.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_compositions.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_currency.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_decimal.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_impl.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_parsednumber.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_scientific.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_symbols.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numparse_validators.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numrange_capi.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numrange_fluent.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numrange_impl.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/numsys.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/olsontz.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/persncal.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/pluralranges.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/plurfmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/plurrule.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/quant.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/quantityformatter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/rbnf.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/rbt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/rbt_data.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/rbt_pars.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/rbt_rule.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/rbt_set.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/rbtz.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/regexcmp.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/regeximp.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/regexst.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/regextxt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/region.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/reldatefmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/reldtfmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/rematch.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/remtrans.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/repattrn.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/rulebasedcollator.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/scientificnumberformatter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/scriptset.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/search.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/selfmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/sharedbreakiterator.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/simpletz.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/smpdtfmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/smpdtfst.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/sortkey.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/standardplural.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/string_segment.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/strmatch.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/strrepl.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/stsearch.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/taiwncal.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/timezone.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/titletrn.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/tmunit.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/tmutamt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/tmutfmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/tolowtrn.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/toupptrn.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/translit.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/transreg.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/tridpars.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/tzfmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/tzgnames.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/tznames.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/tznames_impl.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/tzrule.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/tztrans.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/ucal.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/ucln_in.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/ucol.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/ucol_res.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/ucol_sit.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/ucoleitr.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/ucsdet.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/udat.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/udateintervalformat.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/udatpg.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/ufieldpositer.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/uitercollationiterator.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/ulistformatter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/ulocdata.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/umsg.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unesctrn.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/uni2name.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/units_complexconverter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/units_converter.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/units_data.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/units_router.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unum.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/unumsys.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/upluralrules.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/uregex.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/uregexc.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/uregion.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/usearch.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/uspoof.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/uspoof_build.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/uspoof_conf.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/uspoof_impl.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/utf16collationiterator.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/utf8collationiterator.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/utmscale.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/utrans.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/vtzone.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/vzone.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/windtfmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/winnmfmt.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/wintzimpl.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/zonemeta.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/zrule.cpp
  ${PROJECT_SOURCE_DIR}/icu/src/icu4c/source/i18n/ztrans.cpp
)


# # Compiler specific settings
# if(${CMAKE_C_COMPILER_ID} MATCHES "GNU" OR ${CMAKE_C_COMPILER_ID} MATCHES "Clang")
#   add_definitions(-DICU_EXPORT=__attribute__\(\(visibility\("default"\)\)\))
#   set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fvisibility=hidden -std=c99 -pedantic -Wall -Wno-unused-variable")
#   set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fvisibility=hidden -std=c++11 -pedantic -Wall -Wno-unused-variable")
# endif()

# if (MSVC)
#   add_definitions(-DGPKG_CALL=__cdecl)
#   set_target_properties(gpkg_ext PROPERTIES COMPILE_DEFINITIONS "ICU_EXPORT=__declspec\(dllexport\)")
#   set (CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /TP")
# endif()