name: Build Geopackage
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build
        run: |
            docker run \
            -e WORKING_DIR="$PWD" \
            -v $PWD:$PWD alpine:edge $PWD/.github/workflows/build_alpine.sh